mongo 127.0.0.1/local scripts\overall.js >> results\overall-stats.json
mongo 127.0.0.1/local scripts\top-montly-packages_aura.js >> results\top-montly-packages_aura.json
mongo 127.0.0.1/local scripts\top-montly-packages_cakephp.js >> results\top-montly-packages_cakephp.json
mongo 127.0.0.1/local scripts\top-montly-packages_codeigniter.js >> results\top-montly-packages_codeigniter.json
mongo 127.0.0.1/local scripts\top-montly-packages_fuelphp.js >> results\top-montly-packages_fuelphp.json
mongo 127.0.0.1/local scripts\top-montly-packages_yii.js >> results\top-montly-packages_yii.json
mongo 127.0.0.1/local scripts\top-montly-packages_kohana.js >> results\top-montly-packages_kohana.json
mongo 127.0.0.1/local scripts\top-montly-packages_laminas.js >> results\top-montly-packages_laminas.json
mongo 127.0.0.1/local scripts\top-montly-packages_laravel.js >> results\top-montly-packages_laravel.json
mongo 127.0.0.1/local scripts\top-montly-packages_nette.js >> results\top-montly-packages_nette.json
mongo 127.0.0.1/local scripts\top-montly-packages_phalcon.js >> results\top-montly-packages_phalcon.json
mongo 127.0.0.1/local scripts\top-montly-packages_phpixie.js >> results\top-montly-packages_phpixie.json
mongo 127.0.0.1/local scripts\top-montly-packages_symfony.js >> results\top-montly-packages_symfony.json
mongo 127.0.0.1/local scripts\top-montly-packages_slim.js >> results\top-montly-packages_slim.json
mongo 127.0.0.1/local scripts\top-montly-packages_wordpress.js >> results\top-montly-packages_wordpress.json
mongo 127.0.0.1/local scripts\top-montly-packages_zend.js >> results\top-montly-packages_zend.json
mongo 127.0.0.1/local scripts\top-total-packages_aura.js >> results\top-total-packages_aura.json
mongo 127.0.0.1/local scripts\top-total-packages_cakephp.js >> results\top-total-packages_cakephp.json
mongo 127.0.0.1/local scripts\top-total-packages_codeigniter.js >> results\top-total-packages_codeigniter.json
mongo 127.0.0.1/local scripts\top-total-packages_fuelphp.js >> results\top-total-packages_fuelphp.json
mongo 127.0.0.1/local scripts\top-total-packages_yii.js >> results\top-total-packages_yii.json
mongo 127.0.0.1/local scripts\top-total-packages_kohana.js >> results\top-total-packages_kohana.json
mongo 127.0.0.1/local scripts\top-total-packages_laminas.js >> results\top-total-packages_laminas.json
mongo 127.0.0.1/local scripts\top-total-packages_laravel.js >> results\top-total-packages_laravel.json
mongo 127.0.0.1/local scripts\top-total-packages_nette.js >> results\top-total-packages_nette.json
mongo 127.0.0.1/local scripts\top-total-packages_phalcon.js >> results\top-total-packages_phalcon.json
mongo 127.0.0.1/local scripts\top-total-packages_phpixie.js >> results\top-total-packages_phpixie.json
mongo 127.0.0.1/local scripts\top-total-packages_symfony.js >> results\top-total-packages_symfony.json
mongo 127.0.0.1/local scripts\top-total-packages_slim.js >> results\top-total-packages_slim.json
mongo 127.0.0.1/local scripts\top-total-packages_wordpress.js >> results\top-total-packages_wordpress.json
mongo 127.0.0.1/local scripts\top-total-packages_zend.js >> results\top-total-packages_zend.json
PAUSE